# Generated by Django 4.1 on 2023-09-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_camp_type_alter_profile_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='camp_type',
        ),
    ]
