# Generated by Django 4.1 on 2023-09-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_charpercent_product_char_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='char_percent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.charpercent'),
        ),
    ]
