# Generated by Django 4.1 on 2023-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_product_char_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='title',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
