# Generated by Django 4.1 on 2023-09-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_product_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='charity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
