# Generated by Django 4.1 on 2023-09-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_product_charity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
