# Generated by Django 4.1 on 2023-09-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_alter_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='charity_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='charity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
